# -*- coding: utf-8 -*-
"""app code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QsgKDb34sKNEzw0vdyeleuwCVmFqrcCu
"""

app_code = '''
import streamlit as st
import pandas as pd

# -------------------------------
# PAGE SETTINGS
# -------------------------------
st.set_page_config(
    page_title="Smart Attendance System",
    page_icon="🎓",
    layout="wide"
)

# -------------------------------
# TITLE
# -------------------------------
st.title("🎓 Smart Attendance Management System")
st.markdown("### AI-Based Attendance Tracking and Recognition")
st.markdown("---")

# -------------------------------
# SIDEBAR
# -------------------------------
st.sidebar.title("Navigation")
menu = st.sidebar.radio(
    "Go to:",
    ["Home", "Upload Data", "Results", "Analytics", "About Project"]
)

# -------------------------------
# HOME PAGE
# -------------------------------
if menu == "Home":
    st.subheader("Welcome")
    st.write("""
    This system is designed to automate classroom attendance using Artificial Intelligence.

    ### Main Features:
    - Person detection
    - Face recognition
    - Attendance recording
    - Attendance analytics
    - Downloadable attendance reports
    """)

    st.info("Use the sidebar to navigate through the system.")

    st.markdown("### System Workflow")
    st.markdown("""
    1. Upload student reference images
    2. Upload attendance image or video
    3. Run recognition
    4. View attendance results
    5. Download report
    """)

# -------------------------------
# UPLOAD PAGE
# -------------------------------
elif menu == "Upload Data":
    st.subheader("Upload Data")

    st.markdown("### 1. Upload Student Reference Images")
    student_files = st.file_uploader(
        "Upload student images",
        accept_multiple_files=True,
        type=["jpg", "jpeg", "png"]
    )

    if student_files:
        st.success(f"{len(student_files)} student image(s) uploaded successfully.")

    st.markdown("### 2. Upload Attendance Image / Video")
    attendance_file = st.file_uploader(
        "Upload attendance file",
        type=["jpg", "jpeg", "png", "mp4"]
    )

    if attendance_file:
        st.success("Attendance input uploaded successfully.")

    st.markdown("### 3. Run Attendance Recognition")

    if st.button("Run Recognition"):
        recognized_students = ["Selam", "Abebe", "Ruth", "Tseyon"]

        df = pd.DataFrame({
            "Name": recognized_students,
            "Date": ["2026-04-01"] * len(recognized_students),
            "Time": ["08:15:00", "08:15:05", "08:15:12", "08:15:20"],
            "Status": ["Present"] * len(recognized_students)
        })

        st.session_state["attendance_df"] = df
        st.session_state["recognized_students"] = recognized_students

        st.success("Recognition completed successfully!")
        st.balloons()

# -------------------------------
# RESULTS PAGE
# -------------------------------
elif menu == "Results":
    st.subheader("Attendance Results")

    if "attendance_df" in st.session_state:
        df = st.session_state["attendance_df"]

        st.markdown("### Recognized Students")
        for student in df["Name"]:
            st.write(f"✔ {student}")

        st.markdown("### Attendance Table")
        st.dataframe(df, use_container_width=True)

        csv = df.to_csv(index=False).encode("utf-8")
        st.download_button(
            label="Download Attendance CSV",
            data=csv,
            file_name="attendance_results.csv",
            mime="text/csv"
        )

    else:
        st.warning("No attendance data available yet. Please go to Upload Data and run recognition first.")

# -------------------------------
# ANALYTICS PAGE
# -------------------------------
elif menu == "Analytics":
    st.subheader("Attendance Analytics")

    if "attendance_df" in st.session_state:
        df = st.session_state["attendance_df"]

        total_present = len(df)
        total_absent = 0
        attendance_rate = 100

        col1, col2, col3 = st.columns(3)

        col1.metric("Total Present", total_present)
        col2.metric("Total Absent", total_absent)
        col3.metric("Attendance Rate", f"{attendance_rate}%")

        st.markdown("### Attendance Status Distribution")
        status_counts = df["Status"].value_counts()
        st.bar_chart(status_counts)

        st.markdown("### Attendance Preview")
        st.dataframe(df, use_container_width=True)

    else:
        st.warning("No attendance data available yet. Please run recognition first.")

# -------------------------------
# ABOUT PROJECT PAGE
# -------------------------------
elif menu == "About Project":
    st.subheader("About This Project")

    st.write("""
    ### Project Title:
    Smart Attendance Management System

    ### Objective:
    To automate attendance taking using Artificial Intelligence, reducing manual effort and improving efficiency.

    ### Technologies Used:
    - Python
    - Streamlit
    - YOLO (for person detection)
    - DeepFace (for face recognition)
    - Pandas

    ### Current Prototype:
    This Streamlit dashboard demonstrates the front-end interface of the system for user interaction, attendance display, and analytics.
    """)
'''
with open("app.py", "w") as f:
    f.write(app_code)

print("app.py created successfully!")