# -*- coding: utf-8 -*-
"""requirements

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUPHR2-lIV7FbU_ezIFsYPfphZUvyKDi
"""

requirements = '''
streamlit
pandas
'''

with open("requirements.txt", "w") as f:
    f.write(requirements)

print("requirements.txt created successfully!")